### ISSUE TITLE
Empty ILP result output

### ISSUE THREAD

**Issue by Galaxeee** [raphael-group/startle#1]
Hi there,

Thank you for your great work! Recently I have been trying out Startle on my simulated datasets and got the following error:
![image](https://github.com/raphael-group/startle/assets/39555451/baf3ff6e-167b-461a-a0b3-8e2440c37ed9)

I also have all the outputs before parse_ilp_output here: 
[outputs_startle.zip](https://github.com/raphael-group/startle/files/12195341/outputs_startle.zip)

And with the default parameters, Startle runs for 6 hours on the dataset of 1024 cells. How do I set the parameters to run faster without affecting performance?

Thanks,
Xinhai

**Comment by sashitt2** [comment]
Hi Xinhai,

Thank you for your interest in using Startle. Do you have the log file for this run? I will be able to understand the problem if I can see the standard output of the C++ code. I suspect that the model was not feasible and so the ILP-solver did not return a solution.

Edit: Alternatively the ILP-solver timed out.

Regards
Palash

**Comment by Galaxeee** [comment]
Hi Palash,

Thank you for your reply! I have rerun the same command and here is the log of the run. Thanks!
[log.txt](https://github.com/raphael-group/startle/files/12398490/log.txt)

Best,
Xinhai

**Comment by schmidt73** [comment]
Xinhai,

It appears that the issue is that the ILP is not able to find a feasible solution with in the required timeframe. There are a few ways around this issue:

1. You can try to reduce the problem size using `src/nni/prune.py` script, which combines rows of the character matrix with identical genotypes, and then reattaching them after with `src/nni/unprune.py`.
2. You can try our stochastic hill climbing algorithm `startle-nni` which is documented near the end of the README. Empirically, it was demonstrated to provide nearly identical results as the exact ILP, but takes significantly less time to run.

Let us know if you have any success/run into issues with either of these solutions.

Best,
Henri
